language: c
env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "RqtJGDribR1z0ulRR5XQUloxPYQe+GT5q4oBm/MuxocfJldQOkacdilhNEXgJyYbuY+MWgSOd/+Pmt97/2RW4Gj2Judb/1Gt1LKbxMTkaabqWQk03awqipipMDz6MFfgUaz+LQBx5SalEbj0O115OgB7UrlLgDjh38j6z4SfVLV2JcFQo1bhnInE0fiVn1n6ynQYo0JPDT4FacF50ro9utjQ5G8X9GZo5yhZEj/HzusZiScvfErmpQihvJMrAXRJlJD62ze29mainPIJcZZJ5STNNMPdUAC3gl+Oq6G8mMRbVUowaTprqh+IM/n3NMyZM2N1TyiECRS/WDMqu1oiMb4j7orOIlN/M5U7HSpKEZcndtAL2H3/X0Qa8IQlNX62hm+jtxUDNN+UMr2Y+xl7erB2Zm/aZmbtgwEl0NTQv/3zHYp85ix1jYVTcYe8IeKmvvS5O9i4Q6fEdWD1u6rklKFNpLbN7qnte1Dfx8t1PwF/xWtKl/qJRVgdR+0sOoxIbIRmmD7um9lHYFFhsni78y4ba4maXjaue6QD486YMQA6ll8aGzdOwaVn36iiDwYae4PbMcvjbqk0bgaVGt+fqSehTqKogYW0XEnC7ziBqqqvZ/zJASv635Rpe8c9yTOcEmV+CAxjWLQMIDtYlzmQQG3Ya+Usc4bEdeLkibdsO9s="
matrix:
  include:
  - env: TARGET="coverity"
    compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
    addons:
      coverity_scan:
        project:
          name: "libyal/libvsmbr"
          description: "Build submitted via Travis CI"
        notification_email: joachim.metz@gmail.com
        build_command_prepend: "./synclibs.sh && ./autogen.sh && ./configure"
        build_command: "make -j4"
        branch_pattern: master
  - env: TARGET="linux-clang"
    compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - env: TARGET="linux-gcc"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - env: TARGET="macos-clang"
    compiler: clang
    os: osx
    osx_image: xcode8.1
  - env: TARGET="macos-gcc"
    compiler: gcc
    os: osx
    osx_image: xcode8.1
  - env: TARGET="shared"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then sudo apt-get update && sudo apt-mark hold oracle-java9-installer postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-client postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 postgresql-doc && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y && sudo apt-get install -y autopoint; fi
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew update && brew install gettext gnu-sed && brew link --force gettext; fi
  - if test ${TARGET} = "coverity"; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then export SED="/usr/local/bin/gsed"; fi
  - if test ${TARGET} = "shared"; then ./syncsharedlibs.sh --use-head; fi
  - ./synclibs.sh --use-head && ./autogen.sh
  - if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
script:
  - if test ${TRAVIS_OS_NAME} = "linux"; then export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g"); fi
  - if test ${TARGET} != "coverity"; then ./runtests.sh; fi
after_success:
  - if test ${TARGET} = "linux-gcc"; then curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh; fi
